dist: trusty
notifications:
  hipchat:
    rooms:
      secure: XzwVqNcyT0qzVJ5TayVFB4d2ya5DepeWNGWsKWhAIMlbkVCaEFVWJq8MvcnNhDz9h7mqvrI3R6uSiabCOF2YOMLSr4V/ptlDRxUCsrr1f7pIxuOQXGHJo7FBvqxxuW4oGxSP80kSd/Cn2iUS/UcXwnOzj20FLXzXQ0A5NVywsqrqYAb3H9PReHyrAhTETbWZtINgW54CzkDVXmhPj7cregsPEJpM/+Z8jiMuzqYLhcEpXlJUsHnZm9elF+8KCMlWY0WI85A8/Z7aQzIuZfNY75/7yWaXeppnuzAAv31MV1Npw0nS4F9fy9DqS2jQkqYFBvAhWrA85kjMRtrWNtm9GHfJAQqvcoI+gxygfA7thklkQko/gO5KM07sftzWBye0JDT3gts/xOq7FrSuBd+UjFkUJtzm4DgS9JO/AV+bCH3RCREu9vduL+6T9GQOKZkKmTnbf81r8pysNlakrzns1IXDwfr8ecuO3M1tEpwHPoH8XMDdLqi7qCH6LPn+9rtgUONZ9EpgFKpQ/7YJS/vUp/v1coA1g5VOnblhaAD2LFB1asGYinVAQklzGuYrvg3wVnMmEUQAOvqHZyErTtTyduH2BIE0ua2tgSjp9ASEpiWVfGn1vGZ63ein8LR/WeZJ1wRAhkrMvMRamhHzj+1oaC5wJ5F37/t5uBr5ZH/+Npc=
sudo: required
services:
- docker
env:
  global:
  - DOCKER_IMAGE=puppet/lumogon
  - DOCKER_USER=jfryman
  - secure: Q5+WSF1b7tBzaVKWIIAOT4ItlcSj38eVMw5XAWkpw4XRaO1lu1awuvsx2XBDlZaLdcvm6S45HbM/6wX4/ZoBcv0rVx5Bd4ojranXEby4aIwPAxWx4hJ2plIgoQGWcRH576Nh7WumpW+kBllpYI8pcziW6bAA59SsX9OESBsmTK4+dSR8efBWUYQzTccsU0X+x+5HEot2wb/4j6/Xpis1zsMSEWL33j/KLSp3e4CE4DjoFONr3UiSII3RAmHjus/4C47S7bx1JGv3sZgQ96pVt0zZO4Au1Nn+R85caAJqm31Vx7mEDENYnLbfAKuGXWoRzV+1odFDsk5UUwRGEgc+w9+r0nrFfCn22NgCk5R5smmNr7yXbpt3ECLfuEglTkeD6qpyOckf5rgY0y834iQURYhEJPnh6v8f2C1XntDYsgyb0ni9Um6D2CYM4hp7yWw0aW+59Ia5cs/E5JgYIqsHuiAyoVuVcmnMXHhGwD+G8YhGCpahe1u0aNRGifdYmatzBXR8iGUh/RbEpXdIXQmpvgR2bFcfnuKIbV/WIVjejzxiFJmjSBYKs93J5BBJww7W8v2+e+WuDs5uiLpYtQFMeqaAua4NwxyQlyEKgAYTCQfy1DsjkKhWiTmlJ2b05LHE30RRKHYVbJRoW51xsTvE43wzmtAQ63vg5PUvwh6xnKs=
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
matrix:
  include:
  - go: 1.8
    language: go
    install: make bootstrap
    script:
    - make dependencies test
  - language: ruby
    rvm: 2.3.4
    cache: bundler
    services: docker
    bundler_args: --without development
    env: PUPPET_GEM_VERSION="~> 4.0"
    install: cd contrib/puppetlabs-lumogon && make bootstrap
    script: make dependencies test
deploy:
- provider: script
  script: make deploy
  skip_cleanup: true
  on:
    all_branches: true
